### ISSUE TITLE
Updates on this action BTW

### ISSUE THREAD

**Issue by ajhalili2006** [MadeByThePinsHub/setup-railway-cli-action#1]
We strongly advise you to subscribe to this issue if you use this action or contributing to the repo. We’ll post about plans for new features and changes so you can make your voice heard before we accidentally break your favorite use case :) I will also post here in case there is any security incident (See our [Security Policy](https://github.com/MadeByThePinsHub/policies/blob/master/SECURITY.md)).

The issue is locked in order to limit the noise for subscribers. Please [open a new issue](https://github.com/MadeByThePinsHub/setup-railway-cli-action/issues/new) if you have any questions or feedback about an update.

## About myself :wave:

Hello there, I'm Andrei Jiroh! I'm the maintainer of this action and btw, I'm also a [Railway user](https://railway.app).

Besides this repo, I also maintain [our official handbook](https://en.handbooksbythepins.gq) and other OSS projects made inside @MadeByThePinsHub, @Community-Lores, @RecapTime, and @code-server-boilerplates. I've also created The Pins team, a team that made for [inclusive and welcoming communities](http://hood.ie/blog/welcoming-communities) and an open-core org. We're welcome for any type of contributions, including docs and user support.

Find me elsewhere: [Twitter](https://twitter.com/Kuys_Potpot), [Telegram](https://t.me/AJHalili2006), and [Keybase](https://keybase.io/ajhalilidevph06)

---

_Adapted from https://github.com/wip/app/issues/89 and https://github.com/RecapTime/verify/issues/1_

**Comment by ajhalili2006** [comment]
The initial release is just released, check the changelog over <https://github.com/MadeByThePinsHub/setup-railway-cli-action/releases/tag/v0.1.0>.

To use, simply replace the usage of @railwayapp CLI's install script on your workflows with this:

```yml
# It will install it for you btw.
- name: Setup Railway CLI
  uses: MadeByThePinsHub/setup-railway-cli-action@v0.1.0
  # using npm? No problem, set npm-mode to true
  with:
     npm-rule: true
  # building from source is broken, so you'll get a warning about that and will be
  # fixed in next minor version, PRs are welcome!
```
